apiVersion: v1
kind: Secret
metadata: 
  name: petunia
type: Opaque
stringData:
  postgres-root-password: postgres
  postgres-nakadi-password: nakadi
  postgres-keycloak-password: keycloak
  valkey-password: password
  keycloak-root-password: password
  keycloak-axillaris-secret: NfW7m0qvhOXcOZN9g3pcyudyrJ0cbACt    
  keycloak-villadiana-secret: miqtl8qIoEuLXXEOzvDmwP63xFWXaNje
 
