apiVersion: v1
kind: Secret
metadata: 
  name: petunia
type: Opaque
stringData:
  postgres-root-password: postgres
  postgres-nakadi-password: nakadi
  postgres-keycloak-password: keycloak
  valkey-password: password
  keycloak-root-password: password
  keycloak-alpicola-secret: 
  keycloak-villadiana-secret:
 
