apiVersion: v1
kind: ConfigMap
metadata:
  name: axillaris
data:
  KEYCLOAK_ISSUER_URI: https://auth.roskenet.de/realms/petunia
  KEYCLOAK_INTROSPECTION_URI: https://auth.roskenet.de/realms/chemicals/protocol/openid-connect/token/introspect
