apiVersion: apps/v1
kind: Deployment
metadata:
  name: villadiana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: villadiana
  template:
    metadata:
      labels:
        app: villadiana
    spec:
      containers:
      - name: villadiana
        image: roskenet/villadiana:3.12.0
        env:
          - name: KEYCLOAK_ISSUER_URI
            value: http://keycloak/realms/petunia
          - name: KEYCLOAK_TOKEN_URI
            value: http://keycloak/realms/petunia/protocol/openid-connect/token
          - name: NAKADI_URI
            value: http://nakadi
          - name: ALLOWED_ORIGINS
            value: https://petunia.roskenet.de
          - name: POST_LOGOUT_REDIRECT
            value: https://petunia.roskenet.de
          - name: POST_LOGIN_REDIRECT
            value: https://petunia.roskenet.de/petunias
          - name: AXILLARIS_URI
            value: http://axillaris
        ports:
        - name: www
          containerPort: 8080

