apiVersion: apps/v1
kind: Deployment
metadata:
  name: villadiana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: villadiana
  template:
    metadata:
      labels:
        app: villadiana
    spec:
      containers:
      - name: villadiana
        image: roskenet/villadiana:3.12.0
        env:
          - name: KEYCLOAK_ISSUER_URI
            value: http://auth.roskenet.de/realms/petunia
          - name: KEYCLOAK_TOKEN_URI
            value: http://auth.roskenet.de/realms/petunia/protocol/openid-connect/token
        ports:
        - name: www
          containerPort: 8080

