apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zookeeper-data
  hostPath:
    path: /mnt/zookeeper-data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-datalog
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zookeeper-datalog
  hostPath:
    path: /mnt/zookeeper-datalog
