image:
  repository: postgres
  tag: "17"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 5432

postgres:
  db: postgres
  user: postgres
  password: postgres

persistence:
  enabled: true
  mountPath: /var/lib/postgresql/data
  hostPath: /mnt/postgres/data

