apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-data
  hostPath:
    path: /mnt/kafka-data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-secrets
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-secrets
  hostPath:
    path: /mnt/kafka-secrets
