# Spring Session Configuration
spring:
  session:
    store-type: redis
    redis:
      namespace: hydrogen:session
    timeout: 30m
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak/realms/petunia   # OIDC discovery
        registration:
          keycloak:
            client-id: hydrogen
            client-secret: o6O4bTqrJKSSI7LYc84d5U0AKZzhgKKN
            authorization-grant-type: authorization_code
            scope: openid,profile,email

  # Redis Configuration
  data:
    redis:
      host: valkey.minikube
      port: 6379
      password: mypassword
