apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      volumes:
      - name: kafka-data
        hostPath:
          path: /mnt/kafka/data
          type: Directory
      - name: kafka-secrets
        hostPath:
          path: /mnt/kafka/secrets
          type: Directory
      containers:
      - name: kafka
        image: bitnami/kafka:3.8
        imagePullPolicy: "IfNotPresent"
        env:
        - name: BITNAMI_DEBUG
          value: "no"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_ENABLE_KRAFT
          value: "no"
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: kafka-data
        - mountPath: /etc/kafka/secrets
          name: kafka-secrets

---

apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
#    protocol: TCP
#    name: api
