spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak/realms/petunia}
        opaquetoken:
          client-id: axillaris
          client-secret: ${KEYCLOAK_SECRET:cKsnVPkC2z4CClyevx5ttoZW9Bu9MGsb}
          introspection-uri: ${KEYCLOAK_INTROSPECTION_URI:http://keycloak/realms/chemicals/protocol/openid-connect/token/introspect}
management:
  otlp:
    metrics:
      export:
        url: http://otel-collector:4318
        step: 10s
  metrics:
    tags:
      service.name: axillaris
  endpoints:
    web:
      exposure:
        include: health
