mode: deployment   # Oder daemonset, je nach Use-Case

image:
  repository: otel/opentelemetry-collector
  tag: "0.129.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4317  # Default OTLP gRPC Port
  name: otel-collector

