apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgresql.conf: |
    # Custom PostgreSQL config
    listen_addresses = '*'
    max_connections = 100
    shared_buffers = 128MB
    max_wal_size = 1GB
    min_wal_size = 64MB
    log_timezone = 'Etc/UTC'
    datestyle = 'iso, mdy'
    timezone = 'Etc/UTC'
    lc_messages = 'en_US.utf8'
    lc_monetary = 'en_US.utf8'
    lc_numeric = 'en_US.utf8'
    lc_time = 'en_US.utf8'
    default_text_search_config = 'pg_catalog.english'
    random_page_cost = 1.0

---

apiVersion: v1
kind: Secret
metadata: 
  name: postgres-admin-credentials
type: Opaque
stringData:
  postgres-password: postgres

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:17.5
          imagePullPolicy: "IfNotPresent"
          command: ["postgres", "-c", "config_file=/etc/postgres-config/postgresql.conf"]         
          env:
            - name: POSTGRES_CONFIG_FILE
              value: /etc/postgres-config/postgresql.conf
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: postgres-admin-credentials
                  key: postgres-password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
            - mountPath: /etc/postgres-config
              name: config
      volumes:
        - name: postgres
          hostPath:
            path: /mnt/postgres/data
            type: Directory
        - name: config
          configMap:
            name: postgres-config

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
