kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-volume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/postgres"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-claim
spec:
  storageClassName: manual
  volumeName: postgres-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
