apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-config
data:
  valkey.conf: |
    requirepass mypassword

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
spec:
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
      - name: valkey
        image: valkey/valkey:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: config
          mountPath: /usr/local/etc/valkey/valkey.conf
          subPath: valkey.conf
        args:
        - valkey-server
        - /usr/local/etc/valkey/valkey.conf
      volumes:
      - name: config
        configMap:
          name: valkey-config

---

apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: default
spec:
  selector:
    app: valkey
  type: ClusterIP
  ports:
    - name: tcp-port
      port: 6379
      targetPort: 6379
      protocol: TCP
