spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak/realms/petunia
        opaquetoken:
          client-id: axillaris
          client-secret: cKsnVPkC2z4CClyevx5ttoZW9Bu9MGsb
          introspection-uri: http://keycloak/realms/chemicals/protocol/openid-connect/token/introspect
