<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>de.roskenet.stocker</groupId>
    <artifactId>build-parent</artifactId>
    <version>1.0.0</version>
    <relativePath>../build-parent/pom.xml</relativePath>
  </parent>

  <artifactId>game-engine-starter</artifactId>

  <name>Game Engine Starter</name>
  <url>http://www.roskenet.de</url>

  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

</project>
