spring:
  session:
    store-type: redis
    redis:
      namespace: petunia:session
    timeout: 3m
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak/realms/petunia   # OIDC discovery
        registration:
          keycloak:
            client-id: villadiana
            client-secret: 6w8HibfpYVEQIgMTKAFXFPMC8NgaOHBU
            authorization-grant-type: authorization_code
            scope: openid,profile,email
  data:
    redis:
      host: valkey
      port: 6379
      password: password

app:
  security:
    allowed-origin-patterns:
      - http://localhost:3000
    post-logout-redirect-uri: http://localhost:3000
    default-login-success-url: http://localhost:3000/petunias