apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: default
spec:
  selector:
    app: valkey
  type: ClusterIP
  ports:
    - name: tcp-port
      port: 6379
      targetPort: 6379
      protocol: TCP
