apiVersion: v1
kind: Secret
metadata: 
  name: petunia-credentials
type: Opaque
stringData:
  postgres-root-password:
  postgres-nakadi-password:
  postgres-keycloak-password:
  redis-password:
  keycloak-root-password:
  keycloak-alpicola-secret: 
  keycloak-villadiana-secret:
 
